---
title: "practical0"
author: "Reona"
date: '2023-05-12'
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) 
library(datasauRus)
```

```{r}
datasaurus_dozen %>%
  count(dataset)
```

```{r}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
```

```{r}
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r}
dino_data %>%
  summarize(r = cor(x, y))
```


```{r}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
```

```{r}
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r}
star_data %>%
  summarize(r = cor(x, y))
```
There is no great difference between correlations of dino plot and star plot.

```{r}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
```

```{r}
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r}
circle_data %>%
  summarize(r = cor(x, y))
```
There is no great difference between correlations of dino plot and star plot.

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```

```{r}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y))
```

